In [3]:
import numpy as np
empleado_01 = np.array([[20222333,45,2,20000],[33456234,40,0,25000],[45432345,41,1,10000]])
print(empleado_01)

[[20222333       45        2    20000]
 [33456234       40        0    25000]
 [45432345       41        1    10000]]


In [8]:
#Empleado que gane mas de 15.000$
def superan_salario_bloque1(empleados):
    empleados_con_buen_sueldo = []
    for empleado in empleado_01:
        if empleado[3] >= 15000:
            empleados_con_buen_sueldo.append(empleado)
    return empleados_con_buen_sueldo
print(superan_salario_bloque1(empleado_01))
#La funcion tuvo complejidad O(n), es decir complejidad lineal


[array([20222333,       45,        2,    20000]), array([33456234,       40,        0,    25000])]


In [9]:
empleado_02 = np.array([[20222333,45,2,20000],[33456234,40,0,25000],[45432345,41,1,10000],[43967304,37,0,12000],[42236276,36,0,18000]])
print(superan_salario_bloque1(empleado_02))

[array([20222333,       45,        2,    20000]), array([33456234,       40,        0,    25000]), array([42236276,       36,        0,    18000])]


In [11]:
#Se altera orden de las columnas
empleado_03 =  np.array([[20222333,20000,45,2],[33456234,25000,40,0],[45432345,10000,41,1],[43967304,12000,37,0],[42236276,18000,36,0]])
def superan_salario_bloque1_nuevo_orden(empleados):
    empleados_con_buen_sueldo=[]
    for empleado in empleados:
        if empleado[1] >= 15000:
            empleados_con_buen_sueldo.append([empleado[0],empleado[2],empleado[3],empleado[1]]) #Restablecemos orden correcto
    return empleados_con_buen_sueldo
print(superan_salario_bloque1_nuevo_orden(empleado_03))

[[20222333, 45, 2, 20000], [33456234, 40, 0, 25000], [42236276, 36, 0, 18000]]


In [14]:
empleado_04 = np.array([[20222333,33456234,45432345,43967304,42236276],[45,40,41,37,36],[2,0,1,0,0],[20000,25000,10000,12000,18000]])
def confeccionando_empleado(empleados,indice_empleado):
    atributos_empleado = []
    for empleado in empleados:
        atributos_empleado.append(empleado[indice_empleado])
    return atributos_empleado



def superan_salario_bloque1_como_columnas(empleados):
    empleados_con_buen_sueldo=[]
    for indice,sueldo in enumerate(empleados[3]):
        if sueldo >= 15000:
            empleados_con_buen_sueldo.append(confeccionando_empleado(empleados,indice))
    return empleados_con_buen_sueldo
print(superan_salario_bloque1_como_columnas(empleado_04))

[[20222333, 45, 2, 20000], [33456234, 40, 0, 25000], [42236276, 36, 0, 18000]]
